Calorie Macro Counter/Controllers/FoodItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Calorie_Macro_Counter.Data;
using Calorie_Macro_Counter.Models;
using Microsoft.AspNetCore.Authorization;

namespace Calorie_Macro_Counter.Controllers
{
    public class FoodItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoodItemsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: FoodItems
        public async Task<IActionResult> Index()
        {
            var foodItems = await _context.FoodItems.ToListAsync();
            var totalCalories = foodItems.Sum(f => f.Calories);
            var totalProtein = foodItems.Sum(f => f.Protein);
            var totalFat = foodItems.Sum(f => f.Fat);
            var totalCarbohydrates = foodItems.Sum(f => f.Carbs);

            var viewModel = new FoodItemIndexViewModel
            {
                FoodItems = foodItems,
                TotalCalories = (int)totalCalories,
                TotalProtein = (int)totalProtein,
                TotalFat = (int)totalFat,
                TotalCarbohydrates = (int)totalCarbohydrates
            };

            return View(viewModel);
        }

        // GET: FoodItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foodItem = await _context.FoodItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foodItem == null)
            {
                return NotFound();
            }

            return View(foodItem);
        }

        // GET: FoodItems/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: FoodItems/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Quantity,Calories,Protein,Carbs,Fat")] FoodItem foodItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(foodItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(foodItem);
        }

        // GET: FoodItems/Edit/5
        public IActionResult Edit()
        {
            return View();
        }



        // POST: FoodItems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Calories,Protein,Fat,Carbohydrates")] FoodItem foodItem)
        {
            if (id != foodItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(foodItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodItemExists(foodItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(foodItem);
        }

        private bool FoodItemExists(int id)
        {
            return _context.FoodItems.Any(e => e.Id == id);
        }

        // GET: FoodItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foodItem = await _context.FoodItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foodItem == null)
            {
                return NotFound();
            }

            return View(foodItem);
        }

        // POST: FoodItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var foodItem = await _context.FoodItems.FindAsync(id);
            if (foodItem != null)
            {
                _context.FoodItems.Remove(foodItem);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        
    }
}

Calorie Macro Counter/Controllers/HomeController.cs
using Calorie_Macro_Counter.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Calorie_Macro_Counter.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}


        public IActionResult Privacy()
		{
			return View();
		}

        public IActionResult Overview()
        {
            return View();
        }

        public IActionResult Routines()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

        public IActionResult BenchPress()
        {
            return View();
        }

        public IActionResult InclineDumbbellPress()
        {
            return View();
        }

        public IActionResult BarDips()
        {
            return View();
        }

        public IActionResult StandingCableChestFly()
        {
            return View();
        }

        public IActionResult OverheadPress()
        {
            return View();
        }

        public IActionResult SeatedDumbbellShoulderPress()
        {
            return View();
        }

        public IActionResult DumbbellLateralRaise()
        {
            return View();
        }

        public IActionResult ReverseDumbbellFly()
        {
            return View();
        }

        public IActionResult Deadlift()
        {
            return View();
        }

        public IActionResult LatPulldown()
        {
            return View();
        }

        public IActionResult PullUp()
        {
            return View();
        }

        public IActionResult BarbellRow()
        {
            return View();
        }

        public IActionResult DumbbellRow()
        {
            return View();
        }

        public IActionResult BarbellCurl()
        {
            return View();
        }

        public IActionResult DumbbellCurl()
        {
            return View();
        }

        public IActionResult HammerCurl()
        {
            return View();
        }

        public IActionResult OverheadCableTricepsExtension()
        {
            return View();
        }

        public IActionResult TricepPushdown()
        {
            return View();
        }

        public IActionResult Squat()
        {
            return View();
        }

        public IActionResult LegExtension()
        {
            return View();
        }

        public IActionResult LegPress()
        {
            return View();
        }

        public IActionResult SeatedLegCurl()
        {
            return View();
        }

        public IActionResult HipThrust()
        {
            return View();
        }

        public IActionResult CableCrunch()
        {
            return View();
        }

        public IActionResult HangingLegRaise()
        {
            return View();
        }

        public IActionResult Crunch()
        {
            return View();
        }

        public IActionResult StandingCalfRaise()
        {
            return View();
        }

        public IActionResult SeatedCalfRaise()
        {
            return View();
        }

        public IActionResult FullBodySplit()
        {
            return View();
        }

        public IActionResult UpperLowerSplit()
        {
            return View();
        }

        public IActionResult PushPullLegSplit()
        {
            return View();
        }

        public IActionResult BroClassicBodybuildingSplit()
        {
            return View();
        }

    }
}

Calorie Macro Counter/Views/Home/BarDips.cshtml
@{
    ViewData["Title"] = "Bar Dips";
}

<h1>Bar Dips</h1>

<img src="~/Images/Dips.webp" class="img-thumbnail" alt="~/Images/Dips - 500.webp">

<h2>Muscles Worked in Bar Dips</h2>

<img src="~/Images/Bench-press-muscles-worked.webp" class="img-thumbnail" alt="~/Images/Bench-press-muscles-worked - 500.webp">

<h4>Primary muscles worked:</h4>
<ul>
    <li>Chest</li>
    <li>Front Deltoid</li>
</ul>

<h4>Secondary Muscles worked:</h4>
<ul>
    <li>Triceps</li>
</ul>

<h2>How to do Bar Dips</h2>

<p>1. Grip a dip station about shoulder-width apart, and climb or jump to get into the starting position.</p>
<p>2. Lower yourself with control until your shoulder is below your elbow, or as deep as you comfortably can.</p>
<p>3. Reverse the motion and return to the starting position.</p>

<br />

<p>The bar dip is a classic upper-body exercise, and for most people, heavy enough to give a good training effect with the body weight alone as resistance.</p>

Calorie Macro Counter/Views/Home/BarbellCurl.cshtml
@{
    ViewData["Title"] = "Barbell Curl";
}

<h1>Barbell Curl</h1>

<img src="~/Images/Barbell-biceps-curl.webp" class="img-thumbnail" alt="~/Images/Barbell-biceps-curl - 500.webp">

<h2>Muscles Worked in Barbell Curls</h2>

<img src="~/Images/Muscles-worked-in-the-barbell-curl-2.webp" class="img-thumbnail" alt="~/Images/Muscles-worked-in-the-barbell-curl-2 - 500.webp">

<h4>Primary muscles worked:</h4>
<ul>
    <li>Biceps</li>
</ul>

<h4>Secondary Muscles worked:</h4>
<ul>
    <li>Forearm Flexors</li>
</ul>

<h2>How to Do Barbell Curls</h2>

<p>1. Grip a bar with an underhand (supinated) grip, hands about shoulder-width apart.</p>
<p>2. Lift the bar with control, by flexing your elbows.</p>
<p>3. Don’t let your upper arm travel back during the curl, keep it at your side or move it slightly forward.</p>
<p>4. Reverse the movement and lower the bar back to the starting position.</p>

<br />

<p>The barbell curl is one of the most classic (and best) exercises you can do for your biceps.</p>
<br />
<p>The barbell curl primarily targets your biceps and brachialis (which lie beneath the biceps), but the forearm flexors are also involved as a secondary muscle group.</p>

Calorie Macro Counter/Views/Home/BroClassicBodybuildingSplit.cshtml
@{
    ViewData["Title"] = "BroClassicBodubuildingSplit";
}

<h1>CLASSIC BODYBUILDING SPLIT (AKA BRO SPLIT)</h1>

<h3>5 Day Split:</h3>
<p>Day 1: Legs</p>
<p>Day 2: Chest</p>
<p>Day 3: Back</p>
<p>Day 4: Shoulders</p>
<p>Day 5: Arms & Abs</p>
<p>Day 6-7: Rest </p>

<h4>Leg Workout</h4>
<p>1. Back Squats: 3-4 sets x 5-10 reps</p>
<p>2. Stiff-Leg Deadlifts: 3 sets x 8-12 reps</p>
<p>3. Barbell Hip Thrusts: 3 sets x 8-12 reps</p>
<p>4. Split Squats: 3 sets x 8-12 reps each side</p>
<p>5. Leg Extensions: 2 sets x 10-20 reps</p>
<p>6. Leg Curls: 2 sets x 10-20 reps</p>
<p>7. Calf Raises: 3 sets x 10-20 reps </p>


<h4>Chest Day</h4>
<p>1. Barbell Bench Press: 3-4 sets x 6-12 reps</p>
<p>2. Incline DB Bench Press: 3 sets x 8-15 reps</p>
<p>3. Cable Fly High to Low: 3 sets x 10-15 reps</p>
<p>4. Cable Fly Low to High: 3 sets x 10-15 reps</p>
<p>5. Dips: 3 sets x 10-20 reps </p>

<h4>Back Day</h4>
<p>1. Deadlifts: 3-4 sets x 5-8 reps</p>
<p>2. Pull Ups: 3 sets x max reps</p>
<p>3. Bent Over Barbell Row: 3 sets x 6-12 reps</p>
<p>4. Seated Close Grip Row: 3 sets x 8-15 reps</p>
<p>5. Kroc Row (aka Single Arm Row): 3 sets x 8-15 reps each side </p>
<p>6. Rear Delt Fly: 3 sets x 8-15 reps</p>

<h4>Shoulder Day</h4>
<p>1. Standing Overhead Press: 3-4 sets x 6-12 reps</p>
<p>2. Seated Arnold Press: 3 sets x 8-12 reps</p>
<p>3. Lateral Raises: 3 sets x 10-15 reps</p>
<p>4. Front Raises: 3 sets x 10-15 reps</p>
<p>5. Upright Rows: 3 sets x 10-15 reps</p>
<p>6. Shrugs: 3 sets x 12-20 reps </p>

<h4>Arms & Abs Day</h4>
<p>1. Barbell Bicep Curl: 3 sets x 8-12 reps</p>
<p>2. Alt. Hammer Curl: 2-3 sets x 10-12 reps each</p>
<p>3. Concentration Curl: 2-3 sets x 8-12 reps each side</p>
<p>4. Close Grip Bench: 3 sets x 8-12 reps</p>
<p>5. Tricep Overhead Extension: 2-3 sets x 10-15 reps</p>
<p>6. Tricep Kickback: 2-3 sets x 10-15 reps</p>
<p>7. Hanging Leg Raises: 2 sets x 8-12 reps</p>
<p>8. Plank: 2 sets x 30 sec holds</p>
<p>9. Side Plank: 2 sets x 30 sec hold each side</p>
<p>10. Woodchopper: 2 sets x 10 reps each way</p>

<p>By isolating different muscle groups each day, the bro split allows ample time for recovery for each muscle group. 
    This can be beneficial for muscle growth and repair, as each muscle group gets a full week to recover before being worked again.</p>

Calorie Macro Counter/Views/Home/Deadlift.cshtml
@{
    ViewData["Title"] = "Deadlift";
}

<h1>Deadlift</h1>

<img src="~/Images/Deadlift.webp" class="img-thumbnail" alt="~/Images/Deadlift - 500.webp">

<h2>Muscles Worked in the Deadlift</h2>

<img src="~/Images/Deadlift-muscles-worked.webp" class="img-thumbnail" alt="~/Images/Deadlift-muscles-worked - 500.webp">

<h4>Primary muscles worked:</h4>
<ul>
    <li>Glutes</li>
    <li>Lower Back</li>
</ul>

<h4>Secondary Muscles worked:</h4>
<ul>
    <li>Quads</li>
    <li>Hamstrings</li>
    <li>Adductors</li>
    <li>Trapezius</li>
    <li>Forearm Flexors</li>
</ul>

<h2>How to Deadlift with Proper Form</h2>

<p>1. Step up close to the bar so that it is about over the middle of your foot.</p>
<p>2. Inhale, lean forward, and grip the bar.</p>
<p>3. Hold your breath, brace your core slightly, and lift the bar.</p>
<p>4. Pull the bar close to your body, with a straight back, until you are standing straight.</p>
<p>5. Lower the bar back to the ground with control.</p>
<p>6. Take another breath, and repeat for reps.</p>

<br />

<p>Deadlifting is one of the wisest things you can do with a barbell.</p>
<br />
<p>It strengthens your body from head to toe and puts on slabs of muscle all over you. Deadlift training builds a resilient back and hardens your body into injury-proof armor.</p>

Calorie Macro Counter/Views/Home/DumbbellLateralRaise.cshtml
@{
    ViewData["Title"] = "Dumbbell Lateral Raise";
}

<h1>Dumbbell Lateral Raise</h1>

<img src="~/Images/Dumbbell-Lateral-Raise.webp" class="img-thumbnail" alt="~/Images/Dumbbell-LateralRaise - 500.webp">

<h2>Muscles Worked in the Dumbbell Lateral Raise</h2>

<img src="~/Images/Muscles-worked-by-dumbbell-lateral-raise-2.webp" class="img-thumbnail" alt="~/Images/Muscles-worked-by-dumbbell-lateral-raise-2 - 500.webp">

<h4>Primary muscles worked:</h4>
<ul>
    <li>Lateral Deltoid</li>
</ul>

<h4>Secondary Muscles worked:</h4>
<ul>
    <li>Front Deltoid</li>
</ul>

<h2>How to Do Dumbbell Lateral Raises</h2>

<p>1. Hold a pair of dumbbells in almost straight arms hanging by your sides.</p>
<p>2. With control, lift the dumbbells out to your sides until your upper arms are horizontal.</p>
<p>3. Lower the dumbbells with control.</p>
<p>4. Repeat for reps.</p>

<br />

<p>
    The dumbbell lateral raise is an isolation exercise for primarily the lateral deltoid muscles. 
    This exercise is popular for its ability to sculpt and strengthen the shoulder muscles and is easy to perform since the only equipment you need is a pair of dumbbells.
</p>
<br />
<p>This is an exercise where it is easy to pick a weight that is too heavy. Rather err on the lighter side, and strive for a strict form where you focus on getting a good contact with your delts.</p>

Calorie Macro Counter/Views/Home/FullBodySplit.cshtml
@{
    ViewData["Title"] = "FullBodySplit";
}

<h1>FULL BODY WORKOUT SPLIT</h1>

<p>A full body split involves workouts that target both your upper and lower body each training session, or in other words, full body workouts! This plan is great for many types of lifters and 
    is a favorite workout split among women.</p>

<p>
    However, you aren’t going to be targeting every single muscle in your body each session. Rather, with a total body workout split, you will be performing compound movements that work multiple 
    muscle groups at the same time and allow you to hit your major muscle groups each session.
</p>

<p>
    For example, one full body workout may entail squats, bench press, overhead press, and pull ups, while another has deadlifts, dips, farmer’s walks, and hanging leg raises.
</p>

<p>
    This is a simplified example, but as you can see, with total body workouts you aren’t necessarily specifically targeting every single muscle group each workout, but you are working your full body. Ove the week, you should do at
    least one or two exercises that does specifically target a muscle group. i.e. you should have squats in one of your workouts to target your quads, bench press for your chest, overhead press for your shoulders, and so on.
</p>

<h2>FULL BODY SPLIT OPTIONS: 2, 3, OR 4 DAYS PER WEEK</h2>

<p>Three things to consider with Full Body Splits:</p>
<p>1. Full body workout splits are best done on a 2, 3, or 4 day schedule.</p>
<p>2. Always have a rest day in between sessions. Full body workouts are taxing on the overall nervous system, even for beginners who aren’t lifting heavy.</p>
<p>3. You must hit all major muscle groups each week. Split up your workouts so that you are doing all the main compound lifts throughout the week.</p>
<p>Let's look at the different schedules you can follow with full-body splits.</p>

<h2>2 Day Split:</h2>
<p>Day 1: Full Body Workout</p>
<p>Day 2: Rest</p>
<p>Day 3: Rest</p>
<p>Day 4: Full Body Workout</p>
<p>Day 5-7: Rest</p>

<h4>Workout 1:</h4>
<p>1. Squats: 4 sets x 6-12 reps</p>
<p>2. Bench Press: 4 sets x 6-12 reps</p>
<p>3. Seated DB Shoulder Press: 3 sets x 10-15 reps</p>
<p>4. Rows: 3 sets x 8-15 reps</p>
<p>5. Hanging Leg Raises: 3 sets x 6-12 reps</p>

<h4>Workout 2:</h4>
<p>1. Deadlifts: 4 sets x 6-10 reps</p>
<p>2. Overhead Press: 4 sets x 8-12 reps</p>
<p>3. Pull Ups: 3 sets x max reps</p>
<p>4. DB incline Press: 3 sets x 10-15 reps</p>
<p>5. Planks: 3 sets x 30-60 second holds</p>

<h2>3 Day Split:</h2>
<p>Day 1: Full Body Workout</p>
<p>Day 2: Rest</p>
<p>Day 3: Full Body Workout</p>
<p>Day 4: Rest</p>
<p>Day 5: Full Body Workout</p>
<p>Day 6 & 7: Rest</p>

<h4>Workout 1:</h4>
<p>1. Squats: 4 sets x 6-12 reps</p>
<p>2. Overhead Press: 4 sets x 6-12 reps</p>
<p>3. Rows: 3 sets x 10-15 reps</p>
<p>4. Dips: 3 sets x 8-15 reps</p>

<h4>Workout 2:</h4>
<p>1. Bench Press: 4 sets x 6-12 reps</p>
<p>2. Pull Ups: 3 sets x max reps</p>
<p>3. Split Squats: 3 sets x 8-12 reps each side</p>
<p>4. Planks: 3 sets x 30-60 second holds</p>

<h4>Workout 3:</h4>
<p>1. Deadlifts: 4 sets x 6-10 reps</p>
<p>2. Seated DB Overhead Press: 4 sets x 10-15 reps</p>
<p>3. Push Ups: 3 sets x 15-20+ reps</p>
<p>4. Hanging Leg Raises: 3 sets x 8-12 reps</p>


<h3>4 Day Split:</h3>
<p>Day 1: Full Body Workout</p>
<p>Day 2: Rest</p>
<p>Day 3: Full Body Workout</p>
<p>Day 4: Rest</p>
<p>Day 5: Full Body Workout</p>
<p>Day 6: Rest</p>
<p>Day 7: Full Body Workout</p>
<p>Day 8: Rest</p>
<p>Repeat</p>

<h4>Workout 1:</h4>
<p>1. Standing Overhead Press: 4 sets x 6-12 reps</p>
<p>2. Hip Thrusts: 3 sets x 8-15 reps</p>
<p>3. Pull Ups: 4 sets x Max reps</p>
<p>4. Dips: 3 sets x 10-15 reps</p>

<h4>Workout 2:</h4>
<p>1. Squats: 4 sets x 6-12 reps</p>
<p>2. Incline DB Bench Press: 3 sets x 10-15 reps</p>
<p>3. Seated Rows: 3 sets x 10-15 reps</p>
<p>4. Leg Raises: 3 sets x 8-12 reps </p>

<h4>Workout 3:</h4>
<p>1. Bench Press: 4 sets x 6-12 reps</p>
<p>2. Bent Over Barbell Row: 3 sets x 8-12 reps</p>
<p>3. Split Squats: 3 sets x 8-12 reps each side</p>
<p>4. Bicep Curl x Tricep Extension: 2 sets x 10-20 reps each</p>

<h4>Workout 4:</h4>
<p>1. Deadlifts: 4 sets x 6-10 reps</p>
<p>2. Seated DB Overhead Press: 3 sets x 10-15 reps</p>
<p>3. Chest Fly or DB Pull Overs: 3 sets x 10-15 reps</p>
<p>4. Planks: 3 sets x 30-60 second holds</p>

Calorie Macro Counter/Views/Home/HipThrust.cshtml
@{
    ViewData["Title"] = "Hip Thrust";
}

<h1>Hip Thrust</h1>

<img src="~/Images/Hip-thrust.webp" class="img-thumbnail" alt="~/Images/Hip-thrust - 500.webp">

<h2>Muscles Worked in Hip Thrusts</h2>

<img src="~/Images/Muscles-worked-in-barbell-hip-thrust.webp" class="img-thumbnail" alt="~/Images/Muscles-worked-in-barbell-hip-thrust - 500.webp">

<h4>Primary muscles worked:</h4>
<ul>
    <li>Glutes</li>
</ul>

<h4>Secondary Muscles worked:</h4>
<ul>
    <li>Adductors</li>
    <li>Quads</li>
</ul>

<h2>How to Do Hip Thrust</h2>

<p>1. Sit on the floor with your back against a sturdy bench.</p>
<p>2. Roll the barbell up over your thighs, until it is placed over your hips.</p>
<p>3. Place your feet on the floor, about shoulder-width apart, with bent knees.</p>
<p>4. Place your hands on the bar to stabilize it.</p>
<p>5. Push the bar towards the ceiling by extending your hips. Your knees should form a ~90 degree angle at the top.</p>
<p>6. Lower the weight and repeat for reps.</p>

<br />

<p>
    It is recommended to place something between the bar and your pelvis to soften the pressure from the bar, like a folded yoga mat, a towel, or a barbell pad.
</p>

Calorie Macro Counter/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<header>
    <h1>Calorie Macro Counter</h1>
</header>


<div class="container-custom">
    <div class="d-flex justify-content-center">
        <img src="~/Images/food scale.jpg" class="img-thumbnail" alt="Food Scale">
        <img src="~/Images/weight lifting.jpg" class="img-thumbnail" alt="Weight Lifting">
    </div>

    <div class="text-center">
        <h1 class="display-1">Welcome to Calorie Macro Counter</h1>
    </div>

    <div class="text-center">
        <h2 class="display-6">
            It never gets easier, you just get better at it.
        </h2>
    </div>

    <div class="p-3 text-center">
        <strong>This website features:</strong>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">Feature</th>
                    <th scope="col">See Page</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Calorie Macro Calculator</td>
                    <td><a href="@Url.Action("Edit", "FoodItems")" class="btn btn-primary">Calculator</a></td>
                </tr>
                <tr>
                    <td>Complete Exercise Overview</td>
                    <td><a href="@Url.Action("Overview", "Home")" class="btn btn-primary">Overview</a></td>
                </tr>
                <tr>
                    <td>Specific information on each exercise</td>
                    <td>Use links from overview</td>
                </tr>
                <tr>
                    <td>Gym Routines</td>
                    <td><a href="@Url.Action("Routines", "Home")" class="btn btn-primary">Routines</a></td>
                </tr>
            </tbody>
        </table>
    </div>

    <h2>About Calorie Macro Counter</h2>

    <p>
        This website offers a place for members to track and log their daily caloric intake. Additionally, you will be able to keep track of your daily macro nutrients,
        to ensure you are eating correctly to meet your unique, individual fitness goals. We also offer information on many different exercises you may want to incorporate into your gym routine,
        as well as different examples of routines that fit different individuals based on how much time you have available to attend the gym.
    </p>
</div>

<footer>
    &copy; @DateTime.Now.Year - Calorie Macro Counter
</footer>

Calorie Macro Counter/Views/Home/LatPulldown.cshtml
@{
    ViewData["Title"] = "Lat Pulldown";
}

<h1>Lat Pulldown</h1>

<img src="~/Images/lat-pulldown.webp" class="img-thumbnail" alt="~/Images/lat-pulldown - 500.webp">

<h2>Muscles Worked in the Lat Pulldown</h2>

<img src="~/Images/Muscles-worked-by-lat-pulldown.webp" class="img-thumbnail" alt="~/Images/Muscles-worked-by-lat-pulldown - 500.webp">

<h4>Primary muscles worked:</h4>
<ul>
    <li>Lats</li>
</ul>

<h4>Secondary Muscles worked:</h4>
<ul>
    <li>Biceps</li>
    <li>Rear Deltoids</li>
    <li>Forearm Flexors</li>
    <li>Rotator Cuffs</li>
</ul>

<h2>How to do Lat Pulldowns</h2>

<p>1. Begin by adjusting the thigh pad to fit snugly against your thighs to prevent your body from lifting off the seat.</p>
<p>2. Grasp the bar with an overhand (pronated) grip, with your hands slightly wider than shoulder-width apart.</p>
<p>3. Sit with your thighs under the thigh pad, keep your chest up, and look at the bar.</p>
<p>4. Pull the bar down towards your chest, leading with your elbows. Pull until the bar is below your chin or touches your upper chest.</p>
<p>5. Squeeze your shoulder blades together at the bottom of the movement.</p>
<p>6. Exhale and slowly release the bar back up to the starting position.</p>

<br />

<p>The lat pulldown is a classic back exercise that mainly works your lats, biceps, and rear deltoids. It is the fourth most popular exercise of all, according to statistics</p>
<br />
<p>Increased upper body strength. The lat pulldown is an excellent exercise for increasing your upper body pulling strength. This is especially useful if you want to increase your strength for exercises like pull-ups and chin-ups.</p>